modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="MIT License"

[[mods]] #mandatory
modId="mod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Structure Tutorial Mod" #mandatory
credits=""
authors="" #optional
description='''

'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"